server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
    include: oauth
  datasource:
    url: jdbc:h2:tcp://localhost/~/lotto
    # Removed P6Spy driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none  # ?? create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

lotto:
  latest-draw-no: 1172